name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/snowing_light.gif
    - assets/snowing_dark.gif
    - assets/raining_dark.gif
    - assets/raining_light.gif
    - assets/sunny_light.gif
    - assets/sunny_dark.gif
    - assets/cloudy_dark.gif
    - assets/cloudy_light.gif
    - assets/foggy_light.gif
    - assets/foggy_dark.gif
    - assets/thunderstorm_light.gif
    - assets/thunderstorm_dark.gif
    - assets/windy_light.gif
    - assets/windy_dark.gif
    